SmartSecure/urls.py
from django.conf.urls import patterns, url
from SmartSecure import views

urlpatterns = patterns('',
                       url(r'^$', 'SmartSecure.views.dashboard', name='dashboard'),
                       url(r'^about/$', 'SmartSecure.views.about', name='about'),   
                       )

serverBackend/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('SmartSecure.urls')),
    url(r'^login/(?P<linkpath>.*)$', 'SmartSecure.views.login', name='login'),
    url(r'^dashboard/$', 'SmartSecure.views.dashboard', name='dashboard'),
    url(r'^logout/$', 'SmartSecure.views.logout', name='logout'),
    url(r'^register/$', 'SmartSecure.views.register', name='register'),
    url(r'^help/$', 'SmartSecure.views.help', name='help'),
    url(r'^contact/$', 'SmartSecure.views.contact', name='contact'),
    url(r'^about/$', 'SmartSecure.views.about', name='about')
]

SmartSecure/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

SmartSecure/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.safestring import mark_safe
from django import forms
from bson.objectid import ObjectId
import pymongo
from datetime import datetime, date
from common import readable_time, readable_size, convert_datetime
from hashlib import md5

MONGODB_URI = "mongodb://smartsecure:SJSU2016@ds015909.mlab.com:15909/smartsecure"
# MONGODB_URI = "mongodb://taniachanda86:dharmanagar1@ds041164.mongolab.com:41164/go_273"

class SetCookieForm(forms.Form):
    user_name = forms.CharField(label='User Name', max_length=30)
    password = forms.CharField(label='Password', max_length=30)

class DatePicker(forms.Form):
    date = forms.DateField(initial=date.today)


def registered_user(user_name, md5_password):
    try:
        msg = "User_name and password not found"
        client = pymongo.MongoClient(MONGODB_URI)
        db = client.smartsecure
        already_registered = db.SignUpData.find_one({"userId": user_name,
                                                     "password": md5_password})
        if already_registered:
            return (True, msg)
        else:
            user_exists = db.SignUpData.find_one({"userId": user_name})
            if user_exists:
                msg = "User name and password does not match"
                return (False, msg)
            else:
                msg = "Unregistered User"
                return (False, msg)
        return (False, msg)
    except Exception, m:
        print "Error: %s" % m
    return (False, msg)



def login(request, linkpath):
    if request.method == 'POST':
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            form = SetCookieForm(request.POST, label_suffix=': ')
            if form.is_valid():
                user_name = form.cleaned_data['user_name']
                if not user_name:
                    return HttpResponse("Please enter a valid value for User name.")

                password = md5(form.cleaned_data['password']).hexdigest()

                if not password:
                    return HttpResponse("Please enter a valid value for Password")

                print user_name, password

                valid_user, msg = registered_user(user_name, password)
                if not valid_user:
                    context = {
                        'error_message': msg
                    }
                    return render(request,
                                  "SmartSecure/help.html",
                                  context)

                request.COOKIES['smart_user_name'] = user_name
                request.session['smart_user_name'] = user_name
                request.session.modified = True
                max_age = 7 * 24 * 60 * 60  # 7 days

                if linkpath.startswith('/login'):
                    linkpath = linkpath[6:]
                else:
                    linkpath = '/' + linkpath
                response = HttpResponseRedirect(linkpath)
                response.set_cookie('smart_user_name', user_name, max_age=max_age)
                return response
            else:
                # form.cleaned_data['user_name']
                # form.cleaned_data['password']
                message = "Please enter valid value username and password"
                message = '<span style="color:red;">' + message + '</span><br><br>'
                message = mark_safe(message)

                form = SetCookieForm(label_suffix=': ')
                linkpath = "/dashboard"
                context = {
                    'login_page': True,
                    'form': form,
                    'redirect': linkpath,
                    'error_message': message
                }
                request.session.set_test_cookie()
                return render(request,
                              "SmartSecure/login2.html",
                              context)

        else:
            return HttpResponse("Please check if cookies are enabled and reload the page.")
    else:
        request.session.set_test_cookie()
        form = SetCookieForm(label_suffix=': ')
        if linkpath == '':
            linkpath = '/dashboard'
        message = request.session.get('smart_user_name_error', '')
        if message != '':
            message = '<span style="color:red;">' + message + '</span><br><br>'
            message = mark_safe(message)
        context = {
            'login_page': True,
            'form': form,
            'redirect': linkpath,
            'error_message': message
        }
        return render(request,
                      "SmartSecure/login2.html",
                      context)


class RegistrationForm(forms.Form):
    full_name = forms.CharField(label='Full Name', max_length=30)
    phone_number = forms.CharField(label='Phone Number', max_length=30)
    user_name = forms.CharField(label='Email', max_length=30)
    password = forms.CharField(label='Password', max_length=30)


def validate_user(user_name):
    try:
        msg = ""
        client = pymongo.MongoClient(MONGODB_URI)
        db = client.smartsecure
        # locations = db.smartsecure.find_one({"userId": user_name})
        locations = db.smartsecure.find_one({"userId": user_name})
        if locations:
            already_registered = db.SignUpData.find_one({"userId": user_name})
            if already_registered:
                msg = "User already registered."
                return (False, msg)
        else:
            msg = "User has never used the mobile app"
            return (False, msg)
        return (True, msg)
    except Exception, m:
        print "Error: %s" % m
    return (True, msg)
    

def register_user(full_name, phone_number, user_name, password):
    try:
        msg = ""
        client = pymongo.MongoClient(MONGODB_URI)
        db = client.smartsecure
        db.SignUpData.insert({"userId": user_name, 'full_name': full_name,
                              "phone_number": phone_number, "password": password})
        return True
    except Exception, m:
        print "Error: %s" % m
    return False


def register(request, linkpath="/"):
    if request.method == 'POST':
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()
            form = RegistrationForm(request.POST, label_suffix=': ')
            if form.is_valid():
                user_name = form.cleaned_data['user_name']
                if not user_name:
                    return HttpResponse("Please enter a valid value for User name.")

                # password collection
                password = md5(form.cleaned_data['password']).hexdigest()

                if not password:
                    return HttpResponse("Please enter a valid value for Password")

                full_name = form.cleaned_data['full_name']
                phone_number = form.cleaned_data['phone_number']
                valid_user, msg = validate_user(user_name)
                print "----------------------"
                print msg
                if valid_user:
                    print full_name, phone_number, user_name, password
                    
                    request.COOKIES['smart_user_name'] = user_name
                    request.session['smart_user_name'] = user_name
                    request.session.modified = True
                    max_age = 7 * 24 * 60 * 60  # 7 days

                    if linkpath.startswith('/register'):
                        linkpath = linkpath[8:]
                    elif linkpath == "/":
                        linkpath = "/dashboard"
                    else:
                        linkpath = '/' + linkpath
                    response = HttpResponseRedirect(linkpath)
                    response.set_cookie('smart_user_name', user_name, max_age=max_age)
                    # register_data in DB
                    ret = register_user(full_name, phone_number, user_name, password)
                    print ret
                    return response
                else:
                    # User has never used the mobile app
                    # redirect the user to use the mobile app first

                    context = {
                        'error_message': msg
                    }
                    return render(request,
                                  "SmartSecure/help.html",
                                  context)

            else:
                # form.cleaned_data['user_name']
                # form.cleaned_data['password']
                message = "Please enter valid value username and password"
                message = '<span style="color:red;">' + message + '</span><br><br>'
                message = mark_safe(message)

                form = SetCookieForm(label_suffix=': ')
                linkpath = "/dashboard"
                context = {
                    'login_page': True,
                    'form': form,
                    'redirect': linkpath,
                    'error_message': message
                }
                request.session.set_test_cookie()
                return render(request,
                              "SmartSecure/register.html",
                              context)

        else:
            return HttpResponse("Please check if cookies are enabled and reload the page.")
    else:
        request.session.set_test_cookie()
        form = SetCookieForm(label_suffix=': ')
        if linkpath == '':
            linkpath = '/dashboard'
        message = request.session.get('smart_user_name_error', '')
        if message != '':
            message = '<span style="color:red;">' + message + '</span><br><br>'
            message = mark_safe(message)
        context = {
            'login_page': True,
            'form': form,
            'redirect': linkpath,
            'error_message': message
        }
        return render(request,

templates/SmartSecure/about.html
{% extends "base2.html" %}

{% block extra_head %}

<link href="/static/login2_css/animate.min.css" rel="stylesheet">
  <!-- Custom styling plus plugins -->
<link href="/static/login2_css/custom.css" rel="stylesheet">
<link href="/static/login2_css/icheck/flat/green.css" rel="stylesheet">

<style type="text/css">
/*form {
display: inline;
}*/

</style>

{% endblock %}

{% block content %}

<a class="hiddenanchor" id="toregister"></a>
<a class="hiddenanchor" id="tologin"></a>
<div id="wrapper">
      <div id="login" class="animate form">
        <section class="about_content">
          <form>
          <h1>About SmartSecure</h1>

          <span class="text-warning">
            <b> Special Thanks: We are deeply indebted to Professor Xiao Su, Professor Dan Harkey and Professor Chandrasekar Vupalapatti for their invaluable comments and assistance in the preparation of this project. </b>
          </span>
          <br />
          <span class="text-info">
            In this project, we aimed to build a composite framework or app for Android phones, that will watch user behavior, read patterns and be able to flag suspicious activity. Our approach is to use machine learning and data analytics to record how the users use their phone, the apps most used, the geographical locations the users likely visits and to flag any activity that is deemed to be outside normal. The scope of this project also includes checking the authenticity of Wi-Fi / Bluetooth connections. The outcome is a secure unified app or framework that actively protects and monitors the device and data in multiple ways. 
          </span>
          <span class="text-primary left_align">
            The high–level architecture of this project consists of the SmartSecure app (the frontend and app backend), the Django server and the database.

            Mobile Component
            Frontend: SmartSecure’s frontend is a limited number of screens that allow the user to and change various settings. The UI also includes the popup notifications and security questions that the app generates when it detects abnormal activity on the phone.
            
            <br />

            App backend: The backend accepts the user behavior model from the server. It performs the following tasks:
            
            <br />
            
            o Works in the background to collect user data
            <br />
            
            o Stores the data in its own local database
            <br />
            
            o Compares it against the model
            <br />
            
            o Evolves the model as per new statistics
            <br />

            o Pushes the collected data to the server at regular time intervals
            <br />

            o An Android service that runs continuously to monitor data such as the app usage data, Wi-Fi connectivity details and location data.
            <br />

            o A synchronization service that sends data to and receives data from the cloud server at regular intervals
            <br />

            o A database to temporarily store collected data and permanently store the model received from the cloud server
            <br />

            o A comparison service to compare incoming data with the model.
            <br />

            o A rules based engine to generate proper notifications
            <br />

            SmartSecure database: We are using MongoDb for SmartSecure’s data store.
            <br />

            Web component
            <br />

            The server follows the MVC pattern. It has APIs for the user as well as SmartSecure. It interfaces with MongoLabr on the backend.The serveris deployed on an AWS EC2 instances. 
            <br />

            Frontend : The frontend will comprise webpages to show a dashboard with multiple charts to display app usage statistics
            <br />

            Backend : We are using Django framework to interface with Python APIs for our data processing needs. The backend is written in Python and data is passed among components as JSON.
          </span>
          </form>

          <p class="change_link">New to site?
          <a href="/register" class="to_register"> Create Account </a>
          </p>
          <div class="clearfix"></div>
          <br />
          <div class="clearfix"></div>
          <div class="separator">
            
            <p class="change_link">Already a member ?
            <a href="/login"> Log in </a>
            </p>
            <div class="clearfix"></div>
            <br />
            <div>
              <p>©2016 All Rights Reserved. SmartSecure Privacy and Terms</p>
            </div>
          </div>
        </section>
        <!-- content -->
      </div>
</div>


<!-- Javascript -->
        <!-- <script src="static/js/jquery-2.2.2.min.js"></script>
        <script src="static/bootstrap/js/bootstrap.min.js"></script>
        <script src="static/js/jquery.backstretch.min.js"></script>
        <script src="static/js/scripts.js"></script> -->
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->
{% endblock %}

templates/SmartSecure/contact.html
{% extends "base2.html" %}

{% block extra_head %}

<link href="/static/login2_css/animate.min.css" rel="stylesheet">
  <!-- Custom styling plus plugins -->
<link href="/static/login2_css/custom.css" rel="stylesheet">
<link href="/static/login2_css/icheck/flat/green.css" rel="stylesheet">

<style type="text/css">
/*form {
display: inline;
}*/

</style>

{% endblock %}

{% block content %}

<a class="hiddenanchor" id="toregister"></a>
<a class="hiddenanchor" id="tologin"></a>
<div id="wrapper">
      <div id="login" class="animate form">
        <section class="contact_content">
          <form>
          <h1>SmartSecure Contact</h1>
          <div class="clearfix"></div>
          <br />

          <table class="table left_align">
            <tr>
              <th> Name </th>
              <th> Email id </th>
              <th> Phone number </th>
            </tr>
            <tr>
              <td> Apoorva Gouni </td>
              <td> </td>
              <td> </td>
            </tr>
            <tr>
              <td> Mallika Adinath Kulkarni</td>
              <td> mallikak2709@gmail.com</td>
              <td> 408 442 7994 </td>
            </tr>
            <tr>
              <td> Poornima Vijaylaxmi Sanjeevi </td>
              <td> </td>
              <td> </td>
            </tr>
            <tr>
              <td> Tania Chanda</td>
              <td> taniachanda86@gmail.com</td>
              <td> 650 305 9007</td>
            </tr>
          </table>
          </form>
          <div class="separator">
            <div class="clearfix"></div>
            <br />
            <p class="change_link">New to site?
            <a href="/register" class="to_register"> <span class="text-primary">Create Account </span></a>
            </p>
            <div class="clearfix"></div>
            <br />
          </div>
          <div class="clearfix"></div>
          <div class="separator">
            
            <p class="change_link">Already a member ?
            <a href="/login"> <span class="text-primary"> Log in </span></a>
            </p>
            <div class="clearfix"></div>
            <br />
            <div>
              <p>©2016 All Rights Reserved. SmartSecure Privacy and Terms</p>
            </div>
          </div>
        </section>
        <!-- content -->
      </div>
</div>


<!-- Javascript -->
        <!-- <script src="static/js/jquery-2.2.2.min.js"></script>
        <script src="static/bootstrap/js/bootstrap.min.js"></script>
        <script src="static/js/jquery.backstretch.min.js"></script>
        <script src="static/js/scripts.js"></script> -->
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->
{% endblock %}

templates/SmartSecure/help.html
{% extends "base2.html" %}

{% block extra_head %}

<link href="/static/login2_css/animate.min.css" rel="stylesheet">
  <!-- Custom styling plus plugins -->
<link href="/static/login2_css/custom.css" rel="stylesheet">
<link href="/static/login2_css/icheck/flat/green.css" rel="stylesheet">

<style type="text/css">
/*form {
display: inline;
}*/

</style>

{% endblock %}

{% block content %}

<a class="hiddenanchor" id="toregister"></a>
<a class="hiddenanchor" id="tologin"></a>
<div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
          <form>
            <h1>SmartSecure Help</h1>

            <div class="alert alert-danger">
              {{error_message}}
            </div>

            <h2> help goes here </h2>
          </form>
          <p class="change_link">New to site?
          <a href="/register" class="to_register"> Create Account </a>
          </p>
          <div class="clearfix"></div>
          <br />
          <div class="clearfix"></div>
          <div class="separator">
            
            <p class="change_link">Already a member ?
            <a href="/login"> Log in </a>
            </p>
            <div class="clearfix"></div>
            <br />
            <div>
              <p>©2016 All Rights Reserved. SmartSecure Privacy and Terms</p>
            </div>
          </div>
        </section>
        <!-- content -->
      </div>
</div>


<!-- Javascript -->
        <!-- <script src="static/js/jquery-2.2.2.min.js"></script>
        <script src="static/bootstrap/js/bootstrap.min.js"></script>
        <script src="static/js/jquery.backstretch.min.js"></script>
        <script src="static/js/scripts.js"></script> -->
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->
{% endblock %}

templates/SmartSecure/index.html
<!DOCTYPE html>

{% load static %} <!-- New line -->

<html>

    <head>
        <title>Login</title>
    </head>

    <body>
        <h1>Rango says...</h1>
        hello world! <strong>{{ boldmessage }}</strong><br />
        <a href="/login/about/">About</a><br />
        <!-- <img src="{% static "images/simage.JPG" %}" alt="Picture of Us" /> <!-- New line --> -->
    </body>

</html>

templates/SmartSecure/login.html
{% extends "base.html" %}

{% block extra_head %}
<!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/static/sother_css/font-awesome.min.css">
		<link rel="stylesheet" href="/static/other_css/form-elements.css">
        <link rel="stylesheet" href="/static/other_css/style.css">
<style type="text/css">
/*form {
display: inline;
}*/

</style>
{% endblock %}

{% block content %}
<div class="top-content">
        	
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                        	<div class="form-top">
                        		<div class="form-top-left">
                        			<h2>Login to SmartSecure</h2>
                            		<p>Enter your username and password to log in:</p>
                        		</div>
                        		<div class="form-top-right">
                        			<i class="fa fa-key"></i>
                        		</div>
                            </div>

                            <div class="form-bottom">
			                    <form role="form" action="" method="post" class="login-form">
			                    	<div class="form-group">
			                    		<label class="sr-only" for="form-username">Username</label>
			                        	<input type="text" name="form-username" placeholder="Username..." class="form-username form-control" id="form-username">
			                        </div>
			                        <div class="form-group">
			                        	<label class="sr-only" for="form-password">Password</label>
			                        	<input type="password" name="form-password" placeholder="Password..." class="form-password form-control" id="form-password">
			                        </div>
			                        <button type="submit" class="btn">Sign in!</button>
			                    </form>
		                    </div>
                        </div>
                    </div>

                </div>
            </div>
            
</div>

<!-- Javascript -->
        <script src="static/js/jquery-2.2.2.min.js"></script>
        <script src="static/bootstrap/js/bootstrap.min.js"></script>
        <script src="static/js/jquery.backstretch.min.js"></script>
        <script src="static/js/scripts.js"></script>
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->

{% endblock %}

templates/SmartSecure/login2.html
{% extends "base2.html" %}

{% block extra_head %}

<link href="/static/login2_css/animate.min.css" rel="stylesheet">
  <!-- Custom styling plus plugins -->
<link href="/static/login2_css/custom.css" rel="stylesheet">
<link href="/static/login2_css/icheck/flat/green.css" rel="stylesheet">

<style type="text/css">
/*form {
display: inline;
}*/

</style>

{% endblock %}

{% block content %}

<a class="hiddenanchor" id="toregister"></a>
<a class="hiddenanchor" id="tologin"></a>
<div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
          <form action="/login{{ redirect }}" method="post">
            <h1>Login to SmartSecure</h1>

            {% csrf_token %}
            <div>
              <input id="id_user_name" name="user_name" type="text" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input id="id_password" name="password" type="password" class="form-control" placeholder="Password" required="" />
            </div>

            <div>
              <input class="btn btn-default submit" type="submit" value="Login" />
              <a class="reset_pass" href="/login">Clear</a>
            </div>
            <div class="clearfix"></div>
            <div class="separator">

              <p class="change_link">New to site?
                <a href="/register"> Create Account </a>
              </p>
              <div class="clearfix"></div>
              <br />
              <div>
                <p>©2016 All Rights Reserved. SmartSecure Privacy and Terms</p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
      <div id="register" class="animate form">
        <section class="login_content">
          <form>
            <h1>Create Account</h1>
            <div>
              <input type="text" class="form-control" placeholder="Username" required="" />
            </div>
            <div>
              <input type="email" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input type="password" class="form-control" placeholder="Password" required="" />
            </div>
            <div>
              <a class="btn btn-default submit" href="index.html">Submit</a>
            </div>
            <div class="clearfix"></div>
            <div class="separator">

              <p class="change_link">Already a member ?
                <a href="#tologin" class="to_register"> Log in </a>
              </p>
              <div class="clearfix"></div>
              <br />
              <div>
                <!-- <h1><i class="fa fa-paw" style="font-size: 26px;"></i> Gentelella Alela!</h1> -->

                <p>©2016 All Rights Reserved. SmartSecure Privacy and Terms</p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
    </div>


<!-- Javascript -->
        <!-- <script src="static/js/jquery-2.2.2.min.js"></script>
        <script src="static/bootstrap/js/bootstrap.min.js"></script>
        <script src="static/js/jquery.backstretch.min.js"></script>
        <script src="static/js/scripts.js"></script> -->
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->
{% endblock %}

templates/SmartSecure/login3.html
{% extends "base.html" %}

{% block content %}

<br><br>
{{ error_message }}

<form action="/login{{ redirect }}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login" />
</form>

{% endblock %}

{% block jscontent %}
{% endblock %}

templates/SmartSecure/register.html
{% extends "base2.html" %}

{% block extra_head %}

<link href="/static/login2_css/animate.min.css" rel="stylesheet">
  <!-- Custom styling plus plugins -->
<link href="/static/login2_css/custom.css" rel="stylesheet">
<link href="/static/login2_css/icheck/flat/green.css" rel="stylesheet">

<style type="text/css">
/*form {
display: inline;
}*/

</style>

{% endblock %}

{% block content %}

<a class="hiddenanchor" id="toregister"></a>
<a class="hiddenanchor" id="tologin"></a>
<div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content">
          <form action="/register{{ redirect }}" method="post">
            <h1>Register to SmartSecure</h1>

            {% csrf_token %}

            <div>
              <input id="id_full_name" name="full_name" type="text" class="form-control" placeholder="Full Name" required="" />
            </div>
            <div>
              <input id="id_phone_number" name="phone_number" type="phone" class="form-control" placeholder="Phone Number" required="" />
            </div>
              <br />

            <div>
              <input id="id_user_name" name="user_name" type="email" class="form-control" placeholder="Email" required="" />
            </div>
            <div>
              <input id="id_password" name="password" type="password" class="form-control" placeholder="Password" required="" />
            </div>

            <div>
              <input class="btn btn-default submit" type="submit" value="Register" />
            </div>
            <div class="clearfix"></div>
            <div class="separator">

              <div class="clearfix"></div>
              <br />
              <div>
                <p>©2016 All Rights Reserved. SmartSecure Privacy and Terms</p>
              </div>
            </div>
          </form>
          <!-- form -->
        </section>
        <!-- content -->
      </div>
</div>


<!-- Javascript -->
        <!-- <script src="static/js/jquery-2.2.2.min.js"></script>
        <script src="static/bootstrap/js/bootstrap.min.js"></script>
        <script src="static/js/jquery.backstretch.min.js"></script>
        <script src="static/js/scripts.js"></script> -->
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->
{% endblock %}